#!/usr/bin/env bash
# demo/teardown.sh — undo what setup.sh installed, leaving your global config clean.
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP="$REPO_ROOT/demo/app"
MARKETPLACE="pro-dev-skillset"

# Derive the plugin list from the marketplace manifest rather than hardcoding it.
# A hardcoded list silently goes stale every time a plugin is added, which leaves
# plugins installed and enabled after a --clean and lets stale state mask real
# regressions on the next run.
# (read loop rather than `mapfile`, which needs bash 4+; macOS ships bash 3.2)
STACK=()
while IFS= read -r name; do
  [ -n "$name" ] && STACK+=("$name")
done < <(node -e '
  const m = require(process.argv[1] + "/.claude-plugin/marketplace.json");
  for (const p of m.plugins) console.log(p.name);
' "$REPO_ROOT" 2>/dev/null)
if [ "${#STACK[@]}" -eq 0 ]; then
  echo "! could not read plugin list from marketplace.json — falling back to a static list"
  STACK=(pro-starter pro-core pro-pdd pro-execution pro-quality pro-nextjs \
         pro-design pro-motion pro-testing pro-data pro-research pro-spdd pro-gstack)
fi

cd "$APP"
echo "▸ Uninstalling project-scope plugins…"
# pro-starter first: it is the dependency aggregator, so removing it before its
# dependencies avoids leaving orphaned auto-installed entries behind.
for plugin in pro-starter "${STACK[@]}"; do
  claude plugin uninstall "$plugin@$MARKETPLACE" --scope project 2>/dev/null || true
done

echo "▸ Removing the local marketplace registration…"
# Only removes the project-scope declaration in demo/app/.claude/settings.json;
# your user-scope GitHub marketplace of the same name is untouched.
claude plugin marketplace remove "$MARKETPLACE" --scope project 2>/dev/null || true

echo "▸ Removing build/install artifacts…"
rm -rf "$APP/.next" "$APP/node_modules"

# Removed LAST, and re-checked: the claude CLI flushes settings.json
# asynchronously, so a removal placed right after the uninstall calls loses the
# race and the file reappears. demo/app/.claude/ is gitignored and written
# entirely by setup.sh, so nothing here is worth preserving. Leaving it behind
# keeps stale enabledPlugins entries (figma, worktrunk, plugins since renamed)
# that report "failed to load" on the next run for no real reason.
echo "▸ Removing generated project settings…"
for _ in 1 2 3 4 5; do
  rm -rf "$APP/.claude"
  [ -e "$APP/.claude" ] || break
  sleep 1
done
if [ -e "$APP/.claude" ]; then
  echo "! $APP/.claude keeps reappearing — remove it by hand before re-running setup.sh"
fi

echo "Done. demo/app source is left in place; demo/app/.claude is regenerated by setup.sh."
